### PR TITLE
Add show_submit to list of available Assess administration options

### PR DESCRIPTION
**Pull request by keremdaldal**
LRN-16051

### CODE REVIEW

**Comment by flakeparadigm** [comment]
Hey, @keremdaldal -
Did this PR get forgotten last sprint? 😢

**Comment by keremdaldal** [comment]
Looks like it, thanks!

**Comment by keremdaldal** [comment]
@flakeparadigm oops, just remembered that it's useless merging it since we had to revert the assess changes until we do more polish

**Comment by flakeparadigm** [comment]
Woops, sorry about that.

**Pull request merged**
