### PR TITLE
Update Learnosity SDK to the latest version

### PR DESCRIPTION
**Pull request by shtrom**
This PR updates the SDK to the latest version.

Since v0.8.0, the SDK requires the use of `composer` to install it and dependencies, so the `Makefile` has been expanded to hide the added step of getting composer up and running with the least amount of fuss.

A `./get-composer.sh` script is also provided to abstract the steps of downloading a local version.

### CODE REVIEW

**Comment by shtrom** [comment]
Notes: still on hold. We cannot run the build step from Jenkins as it only does a remote merge without a local checkout of the code. Learnosity/salt-states#1457 is an alternative proposal, doing the build when the repo is updated.

**Comment by gonzalozawa** [comment]
@shtrom this is not working for me. It looks like composer is changing the location of the autoload.php files so the SDK is failing on _init_
What steps are you following to upgrade the PHP SDK on the demos site?

**Comment by gonzalozawa** [comment]
Actually, it looks like there were some conflicts during merge that are causing issues. Can you please merge develop to this branch and confirm if that's working fine for you?

**Comment by shtrom** [comment]
@gonzalozawa I'll fix that, thanks.

Please note that this PR is not safe to merge at the moment, as it depends on other parts of our infra.

**Comment by shtrom** [comment]
@gonzalozawa ok, I've rebased onto `develop`, and bit the bullet: I just vendored the SDK and other dependencies. This is actually similar to what we had before, but it's managed in a cleaner way through `composer`. I guess this also makes it easier for beginners, as they no longer need to play with `composer`.

**Comment by gonzalozawa** [comment]
@shtrom thanks for this!
It's working for me, however, it looks like the README.md file still has the previous changes on this PR.
Correct me if I am wrong, but as far as I understand this latest changes, there should be no impact for clients using the demos site so probably no changes to README.md instructions and no need to use composer here https://github.com/Learnosity/learnosity-demos/tree/feature/sdk-composer#using-phps-native-server

**Comment by shtrom** [comment]
Ok, I updated the README. I kept a reference to `composer` for education purposes, but it's at the end now.

**Comment by gonzalozawa** [comment]
@shtrom thanks for that. Looks good to me. I am happy to get this merged now.

**Comment by shtrom** [comment]
Cool. Yes, please do.

**Pull request merged**
